name: Build Javadocs and Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up build JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'zulu'
          java-version: '21'
          check-latest: true
      - name: Build Javadoc
        run: ./mvnw -B -V -e javadoc:javadoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2 # v4.6.3
        with:
          folder: target/site/apidocs
          target-folder: ${{github.ref_name}}
