# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['8', '11', '17']
    steps:
    - uses: actions/checkout@v3
    - name: Set up build JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'maven'
        check-latest: true
    - name: Build with Maven
      run: mvn -B -DskipTests=true package --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
        name: java-jars
        path: |
          **/target/*.jar
          **/target/bom.*
      if: always()
  test:
    needs: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['8', '11', '17']
    steps:
    - name: Set up test JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'
        check-latest: true
    - name: Test with Maven
      run: mvn -B -P coverage verify -Denforcer.skip=true -Dmaven.resources.skip=true -Dmaven.main.skip=true -Dassembly.skipAssembly=true -Dmaven.javadoc.skip=true -DskipITs=false --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
        name: java-${{ matrix.java }}-testresults
        path: |
          **/target/surefire-reports/
          **/target/failsafe-reports/
          **/target/site/jacoco/
          **/target/site/jacoco-it/
      if: always()
